[build]
  publish = "public"
  command = "hugo"
  
[build.environment]
  HUGO_THEME = "repo"
  HUGO_VERSION = "0.68.3"
  HUGO_ENABLEGITINFO = "true"
  
[context.production.environment]
  HUGO_ENV = "production"
  
[context.production.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.68.3"
  
[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"